// <autogenerated>
//   This file was generated by T4 code generator Dto.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

using Mes.Demo.Contracts.TestLog;
using Mes.Demo.Dtos.TestLog;
using Mes.Demo.Models.TestLog;
using Mes.Utility.Data;
using Mes.Utility.Extensions;
using Mes.Web.Mvc.Binders;
using Mes.Web.Mvc.Security;
using Mes.Web.UI;


namespace Mes.Demo.Web.Areas.Admin.Controllers
{
    
    public class OperationLogController : AdminBaseController
    {
        public ITestLogContract TestLogContract { get; set; }



        [AjaxOnly]
        public ActionResult GridData(int? id)
        {
            int total;
            GridRequest request = new GridRequest(Request);
            var datas = GetQueryData<OperationLog, int>(TestLogContract.OperationLogs, out total, request).Select(m => new
            {
                m.Id,
                m.Num,
                m.MoveTimes,
                m.ReadTimes,
                m.ZipTimes,
                m.DeleteTimes,
                m.TotalTimes,
                m.OperationType,
                m.CreatedTime
            });
            return Json(new GridData<object>(datas, total), JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        [AjaxOnly]
        public ActionResult Add([ModelBinder(typeof(JsonBinder<OperationLogDto>))] ICollection<OperationLogDto> dtos)
        {
            dtos.CheckNotNull("dtos");
            OperationResult result = TestLogContract.AddOperationLogs(dtos.ToArray());
            return Json(result.ToAjaxResult(), JsonRequestBehavior.AllowGet);
        }

        
        [HttpPost]
        [AjaxOnly]
        public ActionResult Edit([ModelBinder(typeof(JsonBinder<OperationLogDto>))] ICollection<OperationLogDto> dtos)
        {
            dtos.CheckNotNull("dtos");
            OperationResult result = TestLogContract.EditOperationLogs(dtos.ToArray());
            return Json(result.ToAjaxResult(), JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        [AjaxOnly]
        public ActionResult Delete([ModelBinder(typeof(JsonBinder<int>))] ICollection<int> ids)
        {
            ids.CheckNotNull("ids");
            OperationResult result = TestLogContract.DeleteOperationLogs(ids.ToArray());
            return Json(result.ToAjaxResult(), JsonRequestBehavior.AllowGet);
        }

    }
}
