// <autogenerated>
//   This file was generated by T4 code generator Dto.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Linq;
using System.Linq.Expressions;

using Mes.Core;
using Mes.Demo.Dtos.SiteManagement;
using Mes.Demo.Models.SiteManagement;
using Mes.Utility.Data;


namespace Mes.Demo.Contracts.SiteManagement
{
    public partial interface ISiteManagementContract : IDependency
    {
        /// <summary>
        /// 获取问题类型 信息查询数据集
        /// </summary>
        IQueryable<ProblemType> ProblemTypes { get; }
        
        /// <summary>
        /// 检查问题类型信息是否存在
        /// </summary>
        /// <param name="predicate">检查谓语表达式</param>
        /// <param name="id">更新的问题类型信息编号</param>
        /// <returns>问题类型信息是否存在</returns>
        bool CheckProblemTypeExists(Expression<Func<ProblemType, bool>> predicate, int id = 0);
        
        /// <summary>
        /// 添加问题类型信息
        /// </summary>
        /// <param name="dtos">要添加的问题类型信息DTO信息</param>
        /// <returns>业务操作结果</returns>
        OperationResult AddProblemTypes(params ProblemTypeDto[] dtos);
        
        /// <summary>
        /// 更新问题类型信息
        /// </summary>
        /// <param name="dtos">包含更新信息的问题类型DTO信息</param>
        /// <returns>业务操作结果</returns>
        OperationResult EditProblemTypes(params ProblemTypeDto[] dtos);

        /// <summary>
        /// 删除问题类型信息
        /// </summary>
        /// <param name="ids">要删除的问题类型信息编号</param>
        /// <returns>业务操作结果</returns>
        OperationResult DeleteProblemTypes(params int[] ids);
    }
}
      
