// <autogenerated>
//   This file was generated by T4 code generator Dto.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Linq;
using System.Linq.Expressions;

using Mes.Core;
using Mes.Demo.Dtos.SiteManagement;
using Mes.Demo.Models.SiteManagement;
using Mes.Utility.Data;


namespace Mes.Demo.Contracts.SiteManagement
{
    public partial interface ISiteManagementContract : IDependency
    {
        /// <summary>
        /// 获取问题来源 信息查询数据集
        /// </summary>
        IQueryable<ProblemSource> ProblemSources { get; }
        
        /// <summary>
        /// 检查问题来源信息是否存在
        /// </summary>
        /// <param name="predicate">检查谓语表达式</param>
        /// <param name="id">更新的问题来源信息编号</param>
        /// <returns>问题来源信息是否存在</returns>
        bool CheckProblemSourceExists(Expression<Func<ProblemSource, bool>> predicate, int id = 0);
        
        /// <summary>
        /// 添加问题来源信息
        /// </summary>
        /// <param name="dtos">要添加的问题来源信息DTO信息</param>
        /// <returns>业务操作结果</returns>
        OperationResult AddProblemSources(params ProblemSourceDto[] dtos);
        
        /// <summary>
        /// 更新问题来源信息
        /// </summary>
        /// <param name="dtos">包含更新信息的问题来源DTO信息</param>
        /// <returns>业务操作结果</returns>
        OperationResult EditProblemSources(params ProblemSourceDto[] dtos);

        /// <summary>
        /// 删除问题来源信息
        /// </summary>
        /// <param name="ids">要删除的问题来源信息编号</param>
        /// <returns>业务操作结果</returns>
        OperationResult DeleteProblemSources(params int[] ids);
    }
}
      
