// <autogenerated>
//   This file was generated by T4 code generator Dto.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Mes.Core.Data;
using Mes.Demo.Models.Identity;


namespace Mes.Demo.Dtos.Test
{
	public class LineDto : IAddDto, IEditDto<int>
    {
                   
          public string Name {get;set;}
                   
          public string Remark {get;set;}
                   
          public bool IsAdmin {get;set;}
                   
          public bool IsLocked {get;set;}
                   
          public int Id {get;set;}
                
		
	}
}
