// <autogenerated>
//   This file was generated by T4 code generator Dto.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using Mes.Core.Data.Entity;
using Mes.Demo.Models.SiteManagement;


namespace Mes.Demo.ModelConfigurations.SiteManagement
{
    public class ProblemTypeConfiguration:EntityConfigurationBase<ProblemType,int>
    {
        public ProblemTypeConfiguration()
        {
          
        }
    }
}


      
