// <autogenerated>
//   This file was generated by T4 code generator Dto.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Linq;
using System.Linq.Expressions;
using Mes.Core;
using Mes.Demo.Dtos.Test;
using Mes.Demo.Models.Test;
using Mes.Utility.Data;

namespace Mes.Demo.Contracts
{
	public partial interface ITestContract:IDependency
    {
        /// <summary>
        /// 获取站别 信息查询数据集
        /// </summary>
        IQueryable<Station> Stations { get; }
        
        /// <summary>
        /// 检查站别信息是否存在
        /// </summary>
        /// <param name="predicate">检查谓语表达式</param>
        /// <param name="id">更新的站别信息编号</param>
        /// <returns>站别信息是否存在</returns>
        bool CheckStationExists(Expression<Func<Station, bool>> predicate, int id = 0);
        
        /// <summary>
        /// 添加站别信息
        /// </summary>
        /// <param name="dtos">要添加的站别信息DTO信息</param>
        /// <returns>业务操作结果</returns>
        OperationResult AddStations(params StationDto[] dtos);
        
        /// <summary>
        /// 更新站别信息
        /// </summary>
        /// <param name="dtos">包含更新信息的站别DTO信息</param>
        /// <returns>业务操作结果</returns>
        OperationResult EditStations(params StationDto[] dtos);

        /// <summary>
        /// 删除站别信息
        /// </summary>
        /// <param name="ids">要删除的站别信息编号</param>
        /// <returns>业务操作结果</returns>
        OperationResult DeleteStations(params int[] ids);
    }
}
      
