// <autogenerated>
//   This file was generated by T4 code generator Dto.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Linq;
using System.Linq.Expressions;
using Mes.Core.Data;
using Mes.Demo.Dtos.Test;
using Mes.Demo.Models.Test;
using Mes.Utility;
using Mes.Utility.Data;

namespace Mes.Demo.Services.Test
{
	public partial class TestService
    {        
        public IRepository<Station, int> StationRepository {protected get; set; }

        /// <summary>
        /// 获取站别 信息查询数据集
        /// </summary>
        public IQueryable<Station> Stations { get { return StationRepository.Entities; } }
        
        /// <summary>
        /// 检查站别信息是否存在
        /// </summary>
        /// <param name="predicate">检查谓语表达式</param>
        /// <param name="id">更新的站别信息编号</param>
        /// <returns>站别信息是否存在</returns>
        public bool CheckStationExists(Expression<Func<Station, bool>> predicate, int id = 0)
        {
            return StationRepository.CheckExists(predicate, id);
        }
        /// <summary>
        /// 添加站别信息
        /// </summary>
        /// <param name="dtos">要添加的站别信息DTO信息</param>
        /// <returns>业务操作结果</returns>
        public OperationResult AddStations(params StationDto[] dtos)
        {
            return StationRepository.Insert(dtos);
        }
        
        /// <summary>
        /// 更新站别信息
        /// </summary>
        /// <param name="dtos">包含更新信息的站别DTO信息</param>
        /// <returns>业务操作结果</returns>
        public OperationResult EditStations(params StationDto[] dtos)
        {
            return StationRepository.Update(dtos);
        }

        /// <summary>
        /// 删除站别信息
        /// </summary>
        /// <param name="ids">要删除的站别信息编号</param>
        /// <returns>业务操作结果</returns>
        public OperationResult DeleteStations(params int[] ids)
        {
            return StationRepository.Delete(ids);
        }
    }
}
      
