// <autogenerated>
//   This file was generated by T4 code generator Dto.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using Mes.Core;
using Mes.Core.Data;
using Mes.Demo.Contracts;
using Mes.Demo.Contracts.Test;


namespace Mes.Demo.Services.Test
{
	public partial class TestService :ServiceBase, ITestContract
    {
        public TestService(IUnitOfWork unitOfWork)
            : base(unitOfWork)
        { }
    }
}
      
